/**
 * Connect Agent User Construct
 *
 * Creates a Connect-native agent user for CCP softphone login. The password is
 * generated by Secrets Manager (never baked into the CFN template) and passed
 * to a custom-resource Lambda that calls connect:CreateUser using the default
 * Admin security profile + Basic Routing Profile.
 */

import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as cr from 'aws-cdk-lib/custom-resources';
import * as path from 'path';
import { NagSuppressions } from 'cdk-nag';
import { solutionUserAgent } from '../utils/solution';

export interface ConnectAgentUserProps {
  vpc: ec2.IVpc;
  connectInstanceArn: string;
  connectInstanceId: string;
  /** Connect user name (e.g., "trainee"). */
  username?: string;
  /** Email for IdentityInfo */
  email?: string;
  firstName?: string;
  lastName?: string;
}

export class ConnectAgentUserConstruct extends Construct {
  public readonly username: string;
  public readonly passwordSecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props: ConnectAgentUserProps) {
    super(scope, id);

    const stack = cdk.Stack.of(this);
    this.username = props.username ?? 'trainee';

    const secretEncryptionKey = new kms.Key(this, 'PasswordSecretKey', {
      description: 'KMS key for encrypting Connect agent password secret',
      enableKeyRotation: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // Generated password — retrieved from Secrets Manager via the AWS console / CLI
    this.passwordSecret = new secretsmanager.Secret(this, 'PasswordSecret', {
      description: `Connect CCP login password for ${this.username}`,
      encryptionKey: secretEncryptionKey,
      generateSecretString: {
        excludePunctuation: false,
        includeSpace: false,
        passwordLength: 20,
        requireEachIncludedType: true,
      },
    });

    const lambdaDir = path.join(__dirname, '../../../src/lambda/connect_agent_user_setup');

    const sg = new ec2.SecurityGroup(this, 'CRSg', {
      vpc: props.vpc,
      description: 'Connect agent user setup custom resource Lambda',
      allowAllOutbound: true,
    });

    const logGroup = new logs.LogGroup(this, 'CRLogs', {
      retention: logs.RetentionDays.ONE_WEEK,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const role = new iam.Role(this, 'CRRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      description: 'Execution role for Connect agent user setup custom resource',
      inlinePolicies: {
        CloudWatchLogs: new iam.PolicyDocument({
          statements: [
            new iam.PolicyStatement({
              effect: iam.Effect.ALLOW,
              actions: ['logs:CreateLogGroup'],
              resources: [logGroup.logGroupArn],
            }),
            new iam.PolicyStatement({
              effect: iam.Effect.ALLOW,
              actions: ['logs:CreateLogStream', 'logs:PutLogEvents'],
              resources: [`${logGroup.logGroupArn}:*`],
            }),
          ],
        }),
        VpcNetworkInterface: new iam.PolicyDocument({
          statements: [
            new iam.PolicyStatement({
              effect: iam.Effect.ALLOW,
              actions: [
                'ec2:CreateNetworkInterface',
                'ec2:DescribeNetworkInterfaces',
                'ec2:DeleteNetworkInterface',
              ],
              resources: ['*'],
            }),
          ],
        }),
        ConnectUserManagement: new iam.PolicyDocument({
          statements: [
            new iam.PolicyStatement({
              effect: iam.Effect.ALLOW,
              actions: [
                'connect:CreateUser',
                'connect:DeleteUser',
                'connect:DescribeUser',
                'connect:ListUsers',
                'connect:ListRoutingProfiles',
                'connect:ListSecurityProfiles',
              ],
              resources: [
                props.connectInstanceArn,
                `${props.connectInstanceArn}/*`,
              ],
            }),
          ],
        }),
        ReadPassword: new iam.PolicyDocument({
          statements: [
            new iam.PolicyStatement({
              effect: iam.Effect.ALLOW,
              actions: ['secretsmanager:GetSecretValue'],
              resources: [this.passwordSecret.secretArn],
            }),
            // GetSecretValue on a CMK-encrypted secret also requires kms:Decrypt,
            // which Secrets Manager calls with these credentials on our behalf.
            new iam.PolicyStatement({
              effect: iam.Effect.ALLOW,
              actions: ['kms:Decrypt'],
              resources: [secretEncryptionKey.keyArn],
              conditions: {
                StringEquals: {
                  'kms:ViaService': `secretsmanager.${stack.region}.amazonaws.com`,
                },
              },
            }),
          ],
        }),
      },
    });

    const setupFn = new lambda.Function(this, 'SetupFn', {
      runtime: lambda.Runtime.PYTHON_3_13,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(lambdaDir),
      role,
      architecture: lambda.Architecture.X86_64,
      timeout: cdk.Duration.minutes(2),
      memorySize: 256,
      vpc: props.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      securityGroups: [sg],
      logGroup,
      environment: {
        USER_AGENT_STRING: solutionUserAgent(this),
      },
      description: 'Provisions Connect CCP agent user for call center training',
    });

    const provider = new cr.Provider(this, 'Provider', {
      onEventHandler: setupFn,
      vpc: props.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
    });

    new cdk.CustomResource(this, 'User', {
      serviceToken: provider.serviceToken,
      properties: {
        InstanceId: props.connectInstanceId,
        Username: this.username,
        PasswordSecretArn: this.passwordSecret.secretArn,
        Email: props.email ?? `${this.username}@example.com`,
        FirstName: props.firstName ?? 'Training',
        LastName: props.lastName ?? 'Agent',
      },
    });

    new cdk.CfnOutput(scope, 'ConnectAgentUsername', {
      value: this.username,
      description: 'Connect CCP login username (for trainees)',
    });
    new cdk.CfnOutput(scope, 'ConnectAgentPasswordSecretArn', {
      value: this.passwordSecret.secretArn,
      description: 'Secrets Manager ARN holding the CCP login password (retrieve via `aws secretsmanager get-secret-value`)',
    });

    NagSuppressions.addResourceSuppressions(
      role,
      [
        { id: 'AwsSolutions-IAM5', reason: 'VPC ENI actions do not support resource ARNs.', appliesTo: ['Resource::*'] },
        {
          id: 'AwsSolutions-IAM5',
          reason: 'Log stream names within the specific log group are dynamic. Scoped to the CR log group only.',
          appliesTo: [{ regex: '/Resource::.*\\.Arn>:\\*$/g' } as any],
        },
        {
          id: 'AwsSolutions-IAM5',
          reason: 'Connect user/routing/security profile IDs are dynamic and are discovered at runtime. Scoped to the specific Connect instance.',
          appliesTo: [{ regex: '/Resource::.*instance\\/.*\\/\\*$/g' } as any],
        },
      ],
      true,
    );

    NagSuppressions.addResourceSuppressions(this.passwordSecret, [
      {
        id: 'AwsSolutions-SMG4',
        reason: 'CCP agent password does not require automatic rotation — manually rotated when needed.',
      },
    ]);
  }
}
